#!/bin/bash

echo "🚀 Render Deployment Guide for Whiteboard Backend"
echo "=================================================="
echo ""
echo "Since Railway's free tier is limited, we'll use Render instead!"
echo ""
echo "📋 Steps to deploy:"
echo "1. Go to https://render.com and sign up"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Configure:"
echo "   - Name: whiteboard-backend"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Plan: Free"
echo "5. Click 'Create Web Service'"
echo ""
echo "🎯 Why Render?"
echo "✅ Completely FREE"
echo "✅ Full WebSocket support"
echo "✅ Automatic HTTPS"
echo "✅ Custom domains"
echo "✅ Great developer experience"
echo ""
echo "📱 After deployment:"
echo "- You'll get a URL like: https://your-app.onrender.com"
echo "- Update your frontend to use this new backend URL"
echo "- Test your whiteboard functionality"
echo ""
echo "🔗 Helpful links:"
echo "- Render: https://render.com"
echo "- Docs: https://docs.render.com"
echo "- Community: https://community.render.com"
